In [1]:
!pip install nba_api
!pip install openpyxl
!pip install pyforest

Requirement already satisfied: nba_api in /usr/local/python/3.10.13/lib/python3.10/site-packages (1.4.1)
Requirement already satisfied: certifi<2024.0.0,>=2023.7.22 in /usr/local/python/3.10.13/lib/python3.10/site-packages (from nba_api) (2023.11.17)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /home/codespace/.local/lib/python3.10/site-packages (from nba_api) (1.26.4)
Requirement already satisfied: requests<3.0,>=2.31 in /home/codespace/.local/lib/python3.10/site-packages (from nba_api) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codespace/.local/lib/python3.10/site-packages (from requests<3.0,>=2.31->nba_api) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.10/site-packages (from requests<3.0,>=2.31->nba_api) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/python/3.10.13/lib/python3.10/site-packages (from requests<3.0,>=2.31->nba_api) (2.0.7)
Requirement already satisfied: openpyxl in /usr/local/python/3.10.13/lib/python3.10/site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /usr/local/python/3.10.13/lib/python3.10/site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: pyforest in /usr/local/python/3.10.13/lib/python3.10/site-packages (1.1.0)

In [2]:
import pandas as pd
from pyforest import *

master_train_df = pd.read_csv('/workspaces/707-group-project-aadit2697/project-checkpoint2/master_data/all_seasons_v2 (1).csv')
master_test_df= pd.read_excel('/workspaces/707-group-project-aadit2697/project-checkpoint2/master_data/season2023_testdata_mastertable.xlsx')
print(master_train_df.shape)
print(master_test_df.shape)

(481311, 59)
(55164, 59)

In [3]:
renamed_columns_for_train = {
    'Team_ID': 'team_id', 
    'Game_ID': 'game_id',
    'PLAYER_ID': 'player_id',
    'GAME_DATE': 'game_date',
    'MATCHUP': 'matchup',
    'W': 'team_wins', # per game
    'L': 'team_losses', # per game
    'W_PCT': 'team_win_percentage',
    'MIN_x': 'team_minutes_played',
    'FGM': 'team_field_goals_made',
    'FGA': 'team_field_goals_attempted',
    'FG_PCT': 'team_field_goal_percentage',
    'FG3M': 'team_three_points_made',
    'FG3A': 'team_three_points_attempted',
    'FG3_PCT': 'team_three_point_percentage',
    'FTM': 'team_free_throws_made',
    'FTA': 'team_free_throws_attempted',
    'FT_PCT': 'team_free_throw_percentage',
    'OREB': 'team_offensive_rebounds',
    'DREB': 'team_defensive_rebounds',
    'REB': 'team_total_rebounds',
    'AST': 'team_assists',
    'STL': 'team_steals',
    'BLK': 'team_blocks',
    'TOV': 'team_turnovers',
    'PF': 'team_personal_fouls',
    'PTS': 'team_points',
    'TEAM_ABBREVIATION': 'team_abbreviation',
    'TEAM_CITY': 'team_city',
    'PLAYER_NAME': 'player_name',
    'NICKNAME': 'nickname',
    'START_POSITION': 'start_position',
    'COMMENT': 'comment',
    'MIN_y': 'minutes_played_player_per_game',
    'E_OFF_RATING': 'estimated_offensive_rating',
    'OFF_RATING': 'offensive_rating',
    'E_DEF_RATING': 'estimated_defensive_rating',
    'DEF_RATING': 'defensive_rating',
    'E_NET_RATING': 'estimated_net_rating',
    'NET_RATING': 'net_rating',
    'AST_PCT': 'assist_percentage',
    'AST_TOV': 'assist_to_turnover_ratio',
    'AST_RATIO': 'assist_ratio',
    'OREB_PCT': 'offensive_rebound_percentage',
    'DREB_PCT': 'defensive_rebound_percentage',
    'REB_PCT': 'rebound_percentage',
    'TM_TOV_PCT': 'team_turnover_percentage',
    'EFG_PCT': 'effective_field_goal_percentage',
    'TS_PCT': 'true_shooting_percentage',
    'USG_PCT': 'usage_percentage',
    'E_USG_PCT': 'estimated_usage_percentage',
    'E_PACE': 'estimated_pace',
    'PACE': 'pace', 
    'PACE_PER40': 'pace_per_40_minutes',
    'POSS': 'possessions',
    'PIE': 'player_impact_estimate',
    'WL': 'win_loss'
}

In [4]:
master_train_df.rename(columns=renamed_columns_for_train, inplace=True)
master_train_df.head()

,team_id,game_id,game_date,matchup,win_loss,team_wins,team_losses,team_win_percentage,team_minutes_played,team_field_goals_made,...,team_turnover_percentage,effective_field_goal_percentage,true_shooting_percentage,usage_percentage,estimated_usage_percentage,estimated_pace,pace,pace_per_40_minutes,possessions,player_impact_estimate
0,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,42,30,0.583,240,45,...,6.5,0.545,0.546,0.357,0.360,109.99,106.60,88.83,60,0.182
1,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,42,30,0.583,240,45,...,6.3,0.417,0.478,0.195,0.198,106.36,102.23,85.20,65,0.087
2,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,42,30,0.583,240,45,...,13.3,0.545,0.528,0.263,0.270,111.96,107.26,89.38,47,0.145
3,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,42,30,0.583,240,45,...,0.0,0.625,0.625,0.121,0.119,106.92,101.30,84.41,58,0.089
4,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,42,30,0.583,240,45,...,0.0,0.545,0.545,0.169,0.175,100.63,99.02,82.52,59,0.089

In [5]:
master_train_df_without_dupe=master_train_df[~master_train_df.duplicated()]

In [6]:
print(master_train_df.shape)
print(master_train_df_without_dupe.shape)

(481311, 59)
(454697, 59)

In [7]:
master_train_df_without_dupe.columns

Index(['team_id', 'game_id', 'game_date', 'matchup', 'win_loss', 'team_wins',
       'team_losses', 'team_win_percentage', 'team_minutes_played',
       'team_field_goals_made', 'team_field_goals_attempted',
       'team_field_goal_percentage', 'team_three_points_made',
       'team_three_points_attempted', 'team_three_point_percentage',
       'team_free_throws_made', 'team_free_throws_attempted',
       'team_free_throw_percentage', 'team_offensive_rebounds',
       'team_defensive_rebounds', 'team_total_rebounds', 'team_assists',
       'team_steals', 'team_blocks', 'team_turnovers', 'team_personal_fouls',
       'team_points', 'GAME_ID', 'TEAM_ID', 'team_abbreviation', 'team_city',
       'player_id', 'player_name', 'nickname', 'start_position', 'comment',
       'minutes_played_player_per_game', 'estimated_offensive_rating',
       'offensive_rating', 'estimated_defensive_rating', 'defensive_rating',
       'estimated_net_rating', 'net_rating', 'assist_percentage',
       'assist_to_turnover_ratio', 'assist_ratio',
       'offensive_rebound_percentage', 'defensive_rebound_percentage',
       'rebound_percentage', 'team_turnover_percentage',
       'effective_field_goal_percentage', 'true_shooting_percentage',
       'usage_percentage', 'estimated_usage_percentage', 'estimated_pace',
       'pace', 'pace_per_40_minutes', 'possessions', 'player_impact_estimate'],
      dtype='object')

In [8]:
master_train_df_without_dupe_wo_team = master_train_df_without_dupe.drop(
    ['team_wins','team_losses', 'team_win_percentage', 'team_minutes_played',
       'team_field_goals_made', 'team_field_goals_attempted',
       'team_field_goal_percentage', 'team_three_points_made',
       'team_three_points_attempted', 'team_three_point_percentage',
       'team_free_throws_made', 'team_free_throws_attempted',
       'team_free_throw_percentage', 'team_offensive_rebounds',
       'team_defensive_rebounds', 'team_total_rebounds', 'team_assists',
       'team_steals', 'team_blocks', 'team_turnovers', 'team_personal_fouls',
       'team_points', 'GAME_ID', 'TEAM_ID'], axis=1
)

In [9]:
master_train_df_without_dupe_wo_team.isnull().sum()

team_id                                 0
game_id                                 0
game_date                               0
matchup                                 0
win_loss                                0
team_abbreviation                       0
team_city                               0
player_id                               0
player_name                             0
nickname                                0
start_position                     276177
comment                            378344
minutes_played_player_per_game      76353
estimated_offensive_rating          76353
offensive_rating                        0
estimated_defensive_rating          76353
defensive_rating                        0
estimated_net_rating                76353
net_rating                              0
assist_percentage                   76353
assist_to_turnover_ratio            76353
assist_ratio                        76353
offensive_rebound_percentage            0
defensive_rebound_percentage            0
rebound_percentage                      0
team_turnover_percentage            76353
effective_field_goal_percentage     76353
true_shooting_percentage            76353
usage_percentage                        0
estimated_usage_percentage              0
estimated_pace                      76353
pace                                76353
pace_per_40_minutes                 76353
possessions                             0
player_impact_estimate              76353
dtype: int64

In [10]:
master_train_df_without_dupe_wo_team.drop('start_position', axis=1, inplace=True)

In [11]:
master_train_df_without_dupe_wo_team.shape[0] - 378344

76353

1. all the variables which starts with estimated will be dropped.
2. dropped start_position
3. all other variables with null values will be filled with 0 except "team_turnover_percentage" as confirmation for data level needs to be done

In [12]:
master_train_df_without_dupe_wo_team.info()

<class 'pandas.core.frame.DataFrame'>
Index: 454697 entries, 0 to 481310
Data columns (total 34 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   team_id                          454697 non-null  int64
 1   game_id                          454697 non-null  int64
 2   game_date                        454697 non-null  object
 3   matchup                          454697 non-null  object
 4   win_loss                         454697 non-null  object
 5   team_abbreviation                454697 non-null  object
 6   team_city                        454697 non-null  object
 7   player_id                        454697 non-null  int64
 8   player_name                      454697 non-null  object
 9   nickname                         454697 non-null  object
 10  comment                          76353 non-null   object
 11  minutes_played_player_per_game   378344 non-null  object
 12  estimated_offensive_rating       378344 non-null  float64
 13  offensive_rating                 454697 non-null  float64
 14  estimated_defensive_rating       378344 non-null  float64
 15  defensive_rating                 454697 non-null  float64
 16  estimated_net_rating             378344 non-null  float64
 17  net_rating                       454697 non-null  float64
 18  assist_percentage                378344 non-null  float64
 19  assist_to_turnover_ratio         378344 non-null  float64
 20  assist_ratio                     378344 non-null  float64
 21  offensive_rebound_percentage     454697 non-null  float64
 22  defensive_rebound_percentage     454697 non-null  float64
 23  rebound_percentage               454697 non-null  float64
 24  team_turnover_percentage         378344 non-null  float64
 25  effective_field_goal_percentage  378344 non-null  float64
 26  true_shooting_percentage         378344 non-null  float64
 27  usage_percentage                 454697 non-null  float64
 28  estimated_usage_percentage       454697 non-null  float64
 29  estimated_pace                   378344 non-null  float64
 30  pace                             378344 non-null  float64
 31  pace_per_40_minutes              378344 non-null  float64
 32  possessions                      454697 non-null  int64
 33  player_impact_estimate           378344 non-null  float64
dtypes: float64(21), int64(4), object(9)
memory usage: 121.4+ MB

In [13]:
master_train_df_without_dupe_wo_team.isnull().sum()

team_id                                 0
game_id                                 0
game_date                               0
matchup                                 0
win_loss                                0
team_abbreviation                       0
team_city                               0
player_id                               0
player_name                             0
nickname                                0
comment                            378344
minutes_played_player_per_game      76353
estimated_offensive_rating          76353
offensive_rating                        0
estimated_defensive_rating          76353
defensive_rating                        0
estimated_net_rating                76353
net_rating                              0
assist_percentage                   76353
assist_to_turnover_ratio            76353
assist_ratio                        76353
offensive_rebound_percentage            0
defensive_rebound_percentage            0
rebound_percentage                      0
team_turnover_percentage            76353
effective_field_goal_percentage     76353
true_shooting_percentage            76353
usage_percentage                        0
estimated_usage_percentage              0
estimated_pace                      76353
pace                                76353
pace_per_40_minutes                 76353
possessions                             0
player_impact_estimate              76353
dtype: int64

In [13]:
minutes_seconds = master_train_df_without_dupe_wo_team['minutes_played_player_per_game'].str.split(':', expand=True)

# Convert minutes and seconds to float and integer respectively
minutes_seconds[0] = minutes_seconds[0].astype(float).fillna(0)  # Convert minutes to float
minutes_seconds[1] = minutes_seconds[1].astype(float).fillna(0)  # Convert seconds to float

# Calculate the decimal format for seconds and adjust minutes
minutes_seconds[1] = minutes_seconds[1] / 60  # Normalize seconds
#print(minutes_seconds[0])
#print(round(minutes_seconds[1],2))
# print(minutes_seconds[0] + round(minutes_seconds[1],2))
master_train_df_without_dupe_wo_team['minutes_played_player_per_game_cln'] = minutes_seconds[0] + round(minutes_seconds[1],2)

In [14]:
master_train_df_without_dupe_wo_team[(master_train_df_without_dupe_wo_team.nickname == "LeBron")][['team_id','game_id','player_id',
                                                                                                   'matchup','game_date',
                                                                                                   'minutes_played_player_per_game',
                                                                                                   'minutes_played_player_per_game_cln']]

,team_id,game_id,player_id,matchup,game_date,minutes_played_player_per_game,minutes_played_player_per_game_cln
0,1610612747,22001072,2544,LAL @ NOP,"MAY 16, 2021",27.000000:28,27.47
27,1610612747,22001061,2544,LAL @ IND,"MAY 15, 2021",28.000000:26,28.43
226,1610612747,22000974,2544,LAL vs. TOR,"MAY 02, 2021",27.000000:33,27.55
252,1610612747,22000956,2544,LAL vs. SAC,"APR 30, 2021",31.000000:51,31.85
807,1610612747,22000640,2544,LAL vs. ATL,"MAR 20, 2021",10.000000:36,10.60
...,...,...,...,...,...,...,...
476579,1610612764,22200349,2544,WAS vs. LAL,"DEC 04, 2022",34.000000:27,34.45
478519,1610612765,22200396,2544,DET vs. LAL,"DEC 11, 2022",36.000000:52,36.87
478848,1610612765,22200234,2544,DET @ LAL,"NOV 18, 2022",NaN,0.00
480366,1610612766,22200551,2544,CHA vs. LAL,"JAN 02, 2023",39.000000:34,39.57
480502,1610612766,22200492,2544,CHA @ LAL,"DEC 23, 2022",33.000000:56,33.93

In [15]:
master_train_df_without_dupe_wo_team.drop('minutes_played_player_per_game', axis=1, inplace=True)

In [16]:
#variable for identifying whether the match was a home match or not
master_train_df_without_dupe_wo_team['home_away'] = master_train_df_without_dupe_wo_team['matchup'].apply(lambda x: 1 if "vs." in x else 0)
master_train_df_without_dupe_wo_team.head()

,team_id,game_id,game_date,matchup,win_loss,team_abbreviation,team_city,player_id,player_name,nickname,...,true_shooting_percentage,usage_percentage,estimated_usage_percentage,estimated_pace,pace,pace_per_40_minutes,possessions,player_impact_estimate,minutes_played_player_per_game_cln,home_away
0,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,LAL,Los Angeles,2544,LeBron James,LeBron,...,0.546,0.357,0.360,109.99,106.60,88.83,60,0.182,27.47,0
1,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,LAL,Los Angeles,203076,Anthony Davis,Anthony,...,0.478,0.195,0.198,106.36,102.23,85.20,65,0.087,30.28,0
2,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,LAL,Los Angeles,203083,Andre Drummond,Andre,...,0.528,0.263,0.270,111.96,107.26,89.38,47,0.145,21.03,0
3,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,LAL,Los Angeles,203484,Kentavious Caldwell-Pope,Kentavious,...,0.625,0.121,0.119,106.92,101.30,84.41,58,0.089,27.48,0
4,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,LAL,Los Angeles,203471,Dennis Schroder,Dennis,...,0.545,0.169,0.175,100.63,99.02,82.52,59,0.089,28.60,0

In [17]:
master_train_df_without_dupe_wo_team.home_away.value_counts()

home_away
1    227391
0    227306
Name: count, dtype: int64

In [18]:
master_train_df_without_dupe_wo_team.columns

Index(['team_id', 'game_id', 'game_date', 'matchup', 'win_loss',
       'team_abbreviation', 'team_city', 'player_id', 'player_name',
       'nickname', 'comment', 'estimated_offensive_rating', 'offensive_rating',
       'estimated_defensive_rating', 'defensive_rating',
       'estimated_net_rating', 'net_rating', 'assist_percentage',
       'assist_to_turnover_ratio', 'assist_ratio',
       'offensive_rebound_percentage', 'defensive_rebound_percentage',
       'rebound_percentage', 'team_turnover_percentage',
       'effective_field_goal_percentage', 'true_shooting_percentage',
       'usage_percentage', 'estimated_usage_percentage', 'estimated_pace',
       'pace', 'pace_per_40_minutes', 'possessions', 'player_impact_estimate',
       'minutes_played_player_per_game_cln', 'home_away'],
      dtype='object')

In [19]:
master_train_df_without_dupe_wo_team['status'] = 'injured'

# Specific condition for 'benched'
master_train_df_without_dupe_wo_team.loc[master_train_df_without_dupe_wo_team['comment'].str.contains("Coach's Decision", na=False), 'status'] = 'Did Not Play'

# Handle NaN values
master_train_df_without_dupe_wo_team['status'] = master_train_df_without_dupe_wo_team['status'].where(
    master_train_df_without_dupe_wo_team['comment'].notna(), 'unknown')

In [20]:
_=master_train_df_without_dupe_wo_team[master_train_df_without_dupe_wo_team.comment.notnull()][['team_id', 'game_id', 
                                                                                              'game_date', 'matchup', 'win_loss',
                                                                                              'team_abbreviation', 'team_city', 
                                                                                              'player_id', 'player_name',
                                                                                              'comment','status']]

In [21]:
_.head()

,team_id,game_id,game_date,matchup,win_loss,team_abbreviation,team_city,player_id,player_name,comment,status
13,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,LAL,Los Angeles,1626149,Montrezl Harrell,DNP - Coach's Decision,Did Not Play
14,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,LAL,Los Angeles,202693,Markieff Morris,DNP - Coach's Decision,Did Not Play
25,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,NOP,New Orleans,1628366,Lonzo Ball,DND - Injury/Illness,injured
26,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,NOP,New Orleans,1628411,Wes Iwundu,DND - Injury/Illness,injured
37,1610612747,22001061,"MAY 15, 2021",LAL @ IND,W,LAL,Los Angeles,1629719,Devontae Cacok,DNP - Coach's Decision,Did Not Play

In [28]:
_.status.value_counts()

status
Did Not Play    64733
injured         11620
Name: count, dtype: int64

In [29]:
master_train_df_without_dupe_wo_team.columns

Index(['team_id', 'game_id', 'game_date', 'matchup', 'win_loss',
       'team_abbreviation', 'team_city', 'player_id', 'player_name',
       'nickname', 'comment', 'estimated_offensive_rating', 'offensive_rating',
       'estimated_defensive_rating', 'defensive_rating',
       'estimated_net_rating', 'net_rating', 'assist_percentage',
       'assist_to_turnover_ratio', 'assist_ratio',
       'offensive_rebound_percentage', 'defensive_rebound_percentage',
       'rebound_percentage', 'team_turnover_percentage',
       'effective_field_goal_percentage', 'true_shooting_percentage',
       'usage_percentage', 'estimated_usage_percentage', 'estimated_pace',
       'pace', 'pace_per_40_minutes', 'possessions', 'player_impact_estimate',
       'minutes_played_player_per_game_cln', 'home_away', 'status'],
      dtype='object')

In [22]:
avg_minutes = master_train_df_without_dupe_wo_team['minutes_played_player_per_game_cln'].mean()
avg_minutes
master_train_df_without_dupe_wo_team['benched_status'] = (master_train_df_without_dupe_wo_team['minutes_played_player_per_game_cln'] < avg_minutes * 0.5).astype(int)

In [23]:
master_train_df_without_dupe_wo_team[master_train_df_without_dupe_wo_team.comment.notnull()][['team_id', 'game_id', 
                                                                                              'game_date', 'matchup', 'win_loss',
                                                                                              'team_abbreviation', 'team_city', 
                                                                                              'player_id', 'player_name',
                                                                                              'comment','status','benched_status']]

,team_id,game_id,game_date,matchup,win_loss,team_abbreviation,team_city,player_id,player_name,comment,status,benched_status
13,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,LAL,Los Angeles,1626149,Montrezl Harrell,DNP - Coach's Decision,Did Not Play,1
14,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,LAL,Los Angeles,202693,Markieff Morris,DNP - Coach's Decision,Did Not Play,1
25,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,NOP,New Orleans,1628366,Lonzo Ball,DND - Injury/Illness,injured,1
26,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,NOP,New Orleans,1628411,Wes Iwundu,DND - Injury/Illness,injured,1
37,1610612747,22001061,"MAY 15, 2021",LAL @ IND,W,LAL,Los Angeles,1629719,Devontae Cacok,DNP - Coach's Decision,Did Not Play,1
...,...,...,...,...,...,...,...,...,...,...,...,...
481278,1610612766,22200017,"OCT 21, 2022",CHA vs. NOP,L,CHA,Charlotte,1631121,Bryce McGowens,DNP - Coach's Decision,Did Not Play,1
481279,1610612766,22200017,"OCT 21, 2022",CHA vs. NOP,L,CHA,Charlotte,1630550,JT Thor,DNP - Coach's Decision,Did Not Play,1
481280,1610612766,22200017,"OCT 21, 2022",CHA vs. NOP,L,CHA,Charlotte,1631109,Mark Williams,DNP - Coach's Decision,Did Not Play,1
481309,1610612766,22200011,"OCT 19, 2022",CHA @ SAS,W,SAS,San Antonio,1631103,Malaki Branham,DNP - Coach's Decision,Did Not Play,1
481310,1610612766,22200011,"OCT 19, 2022",CHA @ SAS,W,SAS,San Antonio,1631104,Blake Wesley,DNP - Coach's Decision,Did Not Play,1

In [24]:
master_train_df_without_dupe_wo_team.benched_status.value_counts()

benched_status
0    328365
1    126332
Name: count, dtype: int64

In [25]:
master_train_df_without_dupe_wo_team.columns

Index(['team_id', 'game_id', 'game_date', 'matchup', 'win_loss',
       'team_abbreviation', 'team_city', 'player_id', 'player_name',
       'nickname', 'comment', 'estimated_offensive_rating', 'offensive_rating',
       'estimated_defensive_rating', 'defensive_rating',
       'estimated_net_rating', 'net_rating', 'assist_percentage',
       'assist_to_turnover_ratio', 'assist_ratio',
       'offensive_rebound_percentage', 'defensive_rebound_percentage',
       'rebound_percentage', 'team_turnover_percentage',
       'effective_field_goal_percentage', 'true_shooting_percentage',
       'usage_percentage', 'estimated_usage_percentage', 'estimated_pace',
       'pace', 'pace_per_40_minutes', 'possessions', 'player_impact_estimate',
       'minutes_played_player_per_game_cln', 'home_away', 'status',
       'benched_status'],
      dtype='object')

In [26]:
master_train_df_without_dupe_wo_team.drop(['estimated_offensive_rating','estimated_defensive_rating',
                                           'estimated_net_rating','estimated_usage_percentage','estimated_pace'], axis=1,
                                           inplace=True)

In [27]:
master_train_df_without_dupe_wo_team.head()

,team_id,game_id,game_date,matchup,win_loss,team_abbreviation,team_city,player_id,player_name,nickname,...,true_shooting_percentage,usage_percentage,pace,pace_per_40_minutes,possessions,player_impact_estimate,minutes_played_player_per_game_cln,home_away,status,benched_status
0,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,LAL,Los Angeles,2544,LeBron James,LeBron,...,0.546,0.357,106.60,88.83,60,0.182,27.47,0,unknown,0
1,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,LAL,Los Angeles,203076,Anthony Davis,Anthony,...,0.478,0.195,102.23,85.20,65,0.087,30.28,0,unknown,0
2,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,LAL,Los Angeles,203083,Andre Drummond,Andre,...,0.528,0.263,107.26,89.38,47,0.145,21.03,0,unknown,0
3,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,LAL,Los Angeles,203484,Kentavious Caldwell-Pope,Kentavious,...,0.625,0.121,101.30,84.41,58,0.089,27.48,0,unknown,0
4,1610612747,22001072,"MAY 16, 2021",LAL @ NOP,W,LAL,Los Angeles,203471,Dennis Schroder,Dennis,...,0.545,0.169,99.02,82.52,59,0.089,28.60,0,unknown,0

In [28]:
import numpy as np
 
# Step 1: Determine the Season Year
# Create a new column 'season_year' to identify the season based on the 'GAME_DATE'

master_train_df_without_dupe_wo_team['game_date'] = pd.to_datetime(master_train_df_without_dupe_wo_team['game_date'], format='%b %d, %Y')

master_train_df_without_dupe_wo_team['season_year'] = np.where(master_train_df_without_dupe_wo_team['game_date'].dt.month >= 10, 
                                      master_train_df_without_dupe_wo_team['game_date'].dt.year, 
                                      master_train_df_without_dupe_wo_team['game_date'].dt.year - 1)
 
# Step 2: Map each season year to a unique season identifier
# First, get the sorted unique season years
unique_season_years = master_train_df_without_dupe_wo_team['season_year'].unique()
unique_season_years.sort()
 
# Create a mapping from season years to "Season1", "Season2", etc.
season_mapping = {year: f'Season_{i+1}' for i, year in enumerate(unique_season_years)}
 
# Map the 'season_year' to the new 'Seasons' column using the mapping
master_train_df_without_dupe_wo_team['seasons'] = master_train_df_without_dupe_wo_team['season_year'].map(season_mapping)
 
# Example output
master_train_df_without_dupe_wo_team[['game_date', 'season_year', 'seasons']].tail(5)

        game_date  season_year   seasons
481306 2022-10-19         2022  Season_8
481307 2022-10-19         2022  Season_8
481308 2022-10-19         2022  Season_8
481309 2022-10-19         2022  Season_8
481310 2022-10-19         2022  Season_8

In [29]:
master_train_df_without_dupe_wo_team.head()

,team_id,game_id,game_date,matchup,win_loss,team_abbreviation,team_city,player_id,player_name,nickname,...,pace,pace_per_40_minutes,possessions,player_impact_estimate,minutes_played_player_per_game_cln,home_away,status,benched_status,season_year,seasons
0,1610612747,22001072,2021-05-16,LAL @ NOP,W,LAL,Los Angeles,2544,LeBron James,LeBron,...,106.60,88.83,60,0.182,27.47,0,unknown,0,2020,Season_6
1,1610612747,22001072,2021-05-16,LAL @ NOP,W,LAL,Los Angeles,203076,Anthony Davis,Anthony,...,102.23,85.20,65,0.087,30.28,0,unknown,0,2020,Season_6
2,1610612747,22001072,2021-05-16,LAL @ NOP,W,LAL,Los Angeles,203083,Andre Drummond,Andre,...,107.26,89.38,47,0.145,21.03,0,unknown,0,2020,Season_6
3,1610612747,22001072,2021-05-16,LAL @ NOP,W,LAL,Los Angeles,203484,Kentavious Caldwell-Pope,Kentavious,...,101.30,84.41,58,0.089,27.48,0,unknown,0,2020,Season_6
4,1610612747,22001072,2021-05-16,LAL @ NOP,W,LAL,Los Angeles,203471,Dennis Schroder,Dennis,...,99.02,82.52,59,0.089,28.60,0,unknown,0,2020,Season_6

In [30]:
master_train_df_without_dupe_wo_team.drop(['season_year','comment'], axis=1, inplace=True)

In [31]:
master_train_df_without_dupe_wo_team.columns

Index(['team_id', 'game_id', 'game_date', 'matchup', 'win_loss',
       'team_abbreviation', 'team_city', 'player_id', 'player_name',
       'nickname', 'comment', 'offensive_rating', 'defensive_rating',
       'net_rating', 'assist_percentage', 'assist_to_turnover_ratio',
       'assist_ratio', 'offensive_rebound_percentage',
       'defensive_rebound_percentage', 'rebound_percentage',
       'team_turnover_percentage', 'effective_field_goal_percentage',
       'true_shooting_percentage', 'usage_percentage', 'pace',
       'pace_per_40_minutes', 'possessions', 'player_impact_estimate',
       'minutes_played_player_per_game_cln', 'home_away', 'status',
       'benched_status', 'seasons'],
      dtype='object')

In [32]:
master_train_df_without_dupe_wo_team.head()

,team_id,game_id,game_date,matchup,win_loss,team_abbreviation,team_city,player_id,player_name,nickname,...,usage_percentage,pace,pace_per_40_minutes,possessions,player_impact_estimate,minutes_played_player_per_game_cln,home_away,status,benched_status,seasons
0,1610612747,22001072,2021-05-16,LAL @ NOP,W,LAL,Los Angeles,2544,LeBron James,LeBron,...,0.357,106.60,88.83,60,0.182,27.47,0,unknown,0,Season_6
1,1610612747,22001072,2021-05-16,LAL @ NOP,W,LAL,Los Angeles,203076,Anthony Davis,Anthony,...,0.195,102.23,85.20,65,0.087,30.28,0,unknown,0,Season_6
2,1610612747,22001072,2021-05-16,LAL @ NOP,W,LAL,Los Angeles,203083,Andre Drummond,Andre,...,0.263,107.26,89.38,47,0.145,21.03,0,unknown,0,Season_6
3,1610612747,22001072,2021-05-16,LAL @ NOP,W,LAL,Los Angeles,203484,Kentavious Caldwell-Pope,Kentavious,...,0.121,101.30,84.41,58,0.089,27.48,0,unknown,0,Season_6
4,1610612747,22001072,2021-05-16,LAL @ NOP,W,LAL,Los Angeles,203471,Dennis Schroder,Dennis,...,0.169,99.02,82.52,59,0.089,28.60,0,unknown,0,Season_6

In [33]:
player_game_team_details = master_train_df_without_dupe_wo_team[['team_id','game_id','game_date','matchup',
                                                                 'team_abbreviation','team_city','player_id','player_name','nickname']]

In [34]:
player_game_team_details.head()

,team_id,game_id,game_date,matchup,team_abbreviation,team_city,player_id,player_name,nickname
0,1610612747,22001072,2021-05-16,LAL @ NOP,LAL,Los Angeles,2544,LeBron James,LeBron
1,1610612747,22001072,2021-05-16,LAL @ NOP,LAL,Los Angeles,203076,Anthony Davis,Anthony
2,1610612747,22001072,2021-05-16,LAL @ NOP,LAL,Los Angeles,203083,Andre Drummond,Andre
3,1610612747,22001072,2021-05-16,LAL @ NOP,LAL,Los Angeles,203484,Kentavious Caldwell-Pope,Kentavious
4,1610612747,22001072,2021-05-16,LAL @ NOP,LAL,Los Angeles,203471,Dennis Schroder,Dennis

In [35]:
master_train_df_without_dupe_wo_team.drop(['team_id','game_id','game_date','matchup',
                                           'team_abbreviation','team_city','player_id',
                                           'player_name','nickname'], axis=1, inplace=True)

In [38]:
master_train_df_without_dupe_wo_team.head()

,win_loss,offensive_rating,defensive_rating,net_rating,assist_percentage,assist_to_turnover_ratio,assist_ratio,offensive_rebound_percentage,defensive_rebound_percentage,rebound_percentage,...,usage_percentage,pace,pace_per_40_minutes,possessions,player_impact_estimate,minutes_played_player_per_game_cln,home_away,status,benched_status,seasons
0,W,103.3,103.2,0.1,0.400,3.0,19.4,0.030,0.000,0.017,...,0.357,106.60,88.83,60,0.182,27.47,0,unknown,0,Season_6
1,W,118.5,101.6,16.9,0.037,1.0,6.3,0.000,0.200,0.083,...,0.195,102.23,85.20,65,0.087,30.28,0,unknown,0,Season_6
2,W,104.3,106.4,-2.1,0.000,0.0,0.0,0.185,0.444,0.289,...,0.263,107.26,89.38,47,0.145,21.03,0,unknown,0,Season_6
3,W,129.3,100.0,29.3,0.222,0.0,42.9,0.000,0.043,0.020,...,0.121,101.30,84.41,58,0.089,27.48,0,unknown,0,Season_6
4,W,110.2,111.9,-1.7,0.182,0.0,26.7,0.000,0.107,0.052,...,0.169,99.02,82.52,59,0.089,28.60,0,unknown,0,Season_6

In [39]:
master_train_df_without_dupe_wo_team.reset_index(inplace=True)
player_game_team_details.reset_index(inplace=True)

In [41]:
master_train_df_without_dupe_wo_team.head()
player_game_team_details.head()

,index,team_id,game_id,game_date,matchup,team_abbreviation,team_city,player_id,player_name,nickname
0,0,1610612747,22001072,2021-05-16,LAL @ NOP,LAL,Los Angeles,2544,LeBron James,LeBron
1,1,1610612747,22001072,2021-05-16,LAL @ NOP,LAL,Los Angeles,203076,Anthony Davis,Anthony
2,2,1610612747,22001072,2021-05-16,LAL @ NOP,LAL,Los Angeles,203083,Andre Drummond,Andre
3,3,1610612747,22001072,2021-05-16,LAL @ NOP,LAL,Los Angeles,203484,Kentavious Caldwell-Pope,Kentavious
4,4,1610612747,22001072,2021-05-16,LAL @ NOP,LAL,Los Angeles,203471,Dennis Schroder,Dennis

In [42]:
print(master_train_df_without_dupe_wo_team.shape)
print(player_game_team_details.shape)

(454697, 24)
(454697, 10)

In [45]:
master_train_df_without_dupe_wo_team.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 454697 entries, 0 to 454696
Data columns (total 24 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   index                               454697 non-null  int64
 1   win_loss                            454697 non-null  object
 2   offensive_rating                    454697 non-null  float64
 3   defensive_rating                    454697 non-null  float64
 4   net_rating                          454697 non-null  float64
 5   assist_percentage                   378344 non-null  float64
 6   assist_to_turnover_ratio            378344 non-null  float64
 7   assist_ratio                        378344 non-null  float64
 8   offensive_rebound_percentage        454697 non-null  float64
 9   defensive_rebound_percentage        454697 non-null  float64
 10  rebound_percentage                  454697 non-null  float64
 11  team_turnover_percentage            378344 non-null  float64
 12  effective_field_goal_percentage     378344 non-null  float64
 13  true_shooting_percentage            378344 non-null  float64
 14  usage_percentage                    454697 non-null  float64
 15  pace                                378344 non-null  float64
 16  pace_per_40_minutes                 378344 non-null  float64
 17  possessions                         454697 non-null  int64
 18  player_impact_estimate              378344 non-null  float64
 19  minutes_played_player_per_game_cln  454697 non-null  float64
 20  home_away                           454697 non-null  int64
 21  status                              454697 non-null  object
 22  benched_status                      454697 non-null  int64
 23  seasons                             454697 non-null  object
dtypes: float64(17), int64(4), object(3)
memory usage: 83.3+ MB

In [46]:
master_train_df_without_dupe_wo_team.isna().sum()

index                                     0
win_loss                                  0
offensive_rating                          0
defensive_rating                          0
net_rating                                0
assist_percentage                     76353
assist_to_turnover_ratio              76353
assist_ratio                          76353
offensive_rebound_percentage              0
defensive_rebound_percentage              0
rebound_percentage                        0
team_turnover_percentage              76353
effective_field_goal_percentage       76353
true_shooting_percentage              76353
usage_percentage                          0
pace                                  76353
pace_per_40_minutes                   76353
possessions                               0
player_impact_estimate                76353
minutes_played_player_per_game_cln        0
home_away                                 0
status                                    0
benched_status                            0
seasons                                   0
dtype: int64

In [48]:
master_train_df_without_dupe_wo_team.fillna(0.0, inplace=True)

In [49]:
master_train_df_without_dupe_wo_team.isna().sum()

index                                 0
win_loss                              0
offensive_rating                      0
defensive_rating                      0
net_rating                            0
assist_percentage                     0
assist_to_turnover_ratio              0
assist_ratio                          0
offensive_rebound_percentage          0
defensive_rebound_percentage          0
rebound_percentage                    0
team_turnover_percentage              0
effective_field_goal_percentage       0
true_shooting_percentage              0
usage_percentage                      0
pace                                  0
pace_per_40_minutes                   0
possessions                           0
player_impact_estimate                0
minutes_played_player_per_game_cln    0
home_away                             0
status                                0
benched_status                        0
seasons                               0
dtype: int64

In [54]:
y=master_train_df_without_dupe_wo_team.win_loss
y_train = pd.Series(np.where(y=="L",0,1))
master_train_df_without_dupe_wo_team.drop('win_loss', axis=1, inplace=True)

In [55]:
master_train_df_without_dupe_wo_team_dum = pd.get_dummies(master_train_df_without_dupe_wo_team, drop_first=True, dtype=int)

In [64]:
y_train.value_counts()

0    227502
1    227195
Name: count, dtype: int64

In [56]:
master_train_df_without_dupe_wo_team_dum

,index,offensive_rating,defensive_rating,net_rating,assist_percentage,assist_to_turnover_ratio,assist_ratio,offensive_rebound_percentage,defensive_rebound_percentage,rebound_percentage,...,benched_status,status_injured,status_unknown,seasons_Season_2,seasons_Season_3,seasons_Season_4,seasons_Season_5,seasons_Season_6,seasons_Season_7,seasons_Season_8
0,0,103.3,103.2,0.1,0.400,3.0,19.4,0.030,0.000,0.017,...,0,0,1,0,0,0,0,1,0,0
1,1,118.5,101.6,16.9,0.037,1.0,6.3,0.000,0.200,0.083,...,0,0,1,0,0,0,0,1,0,0
2,2,104.3,106.4,-2.1,0.000,0.0,0.0,0.185,0.444,0.289,...,0,0,1,0,0,0,0,1,0,0
3,3,129.3,100.0,29.3,0.222,0.0,42.9,0.000,0.043,0.020,...,0,0,1,0,0,0,0,1,0,0
4,4,110.2,111.9,-1.7,0.182,0.0,26.7,0.000,0.107,0.052,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454692,481306,133.3,110.5,22.8,0.000,0.0,0.0,0.000,0.000,0.000,...,1,0,1,0,0,0,0,0,0,1
454693,481307,133.3,110.5,22.8,0.000,0.0,0.0,0.000,0.286,0.125,...,1,0,1,0,0,0,0,0,0,1
454694,481308,133.3,110.5,22.8,0.143,0.0,25.0,0.111,0.286,0.188,...,1,0,1,0,0,0,0,0,0,1
454695,481309,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,...,1,0,0,0,0,0,0,0,0,1
454696,481310,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,...,1,0,0,0,0,0,0,0,0,1

In [65]:
master_train_df_without_dupe_wo_team_dum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 454697 entries, 0 to 454696
Data columns (total 30 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   index                               454697 non-null  int64
 1   offensive_rating                    454697 non-null  float64
 2   defensive_rating                    454697 non-null  float64
 3   net_rating                          454697 non-null  float64
 4   assist_percentage                   454697 non-null  float64
 5   assist_to_turnover_ratio            454697 non-null  float64
 6   assist_ratio                        454697 non-null  float64
 7   offensive_rebound_percentage        454697 non-null  float64
 8   defensive_rebound_percentage        454697 non-null  float64
 9   rebound_percentage                  454697 non-null  float64
 10  team_turnover_percentage            454697 non-null  float64
 11  effective_field_goal_percentage     454697 non-null  float64
 12  true_shooting_percentage            454697 non-null  float64
 13  usage_percentage                    454697 non-null  float64
 14  pace                                454697 non-null  float64
 15  pace_per_40_minutes                 454697 non-null  float64
 16  possessions                         454697 non-null  int64
 17  player_impact_estimate              454697 non-null  float64
 18  minutes_played_player_per_game_cln  454697 non-null  float64
 19  home_away                           454697 non-null  int64
 20  benched_status                      454697 non-null  int64
 21  status_injured                      454697 non-null  int64
 22  status_unknown                      454697 non-null  int64
 23  seasons_Season_2                    454697 non-null  int64
 24  seasons_Season_3                    454697 non-null  int64
 25  seasons_Season_4                    454697 non-null  int64
 26  seasons_Season_5                    454697 non-null  int64
 27  seasons_Season_6                    454697 non-null  int64
 28  seasons_Season_7                    454697 non-null  int64
 29  seasons_Season_8                    454697 non-null  int64
dtypes: float64(17), int64(13)
memory usage: 104.1 MB